<?php
			$optionsArray = array( 'welcome' => array( 'welcomePageSkip' => true,
'welcomeItems' => array( 'expand_menu_button' => array( 'menutItem' => false ),
'collapse_button' => array( 'menutItem' => false ),
'menu' => array( 'menutItem' => false ),
'loginform_login' => array( 'menutItem' => false ),
'username_button' => array( 'menutItem' => false ),
'logo' => array( 'menutItem' => false ),
'expand_button' => array( 'menutItem' => false ),
'welcome_item' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'GLTD',
'page' => 'list' ),
'welcome_item1' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'GltH',
'page' => 'list' ),
'welcome_item2' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'pAccounts',
'page' => 'list' ),
'welcome_item3' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'pCustomer',
'page' => 'list' ),
'welcome_item4' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'pEmployee',
'page' => 'list' ),
'welcome_item5' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'pProductItems',
'page' => 'list' ),
'welcome_item7' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'pSupplier',
'page' => 'list' ),
'welcome_item6' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'psAccountSubGroup',
'page' => 'list' ),
'welcome_item8' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'psChartofAccounts',
'page' => 'list' ),
'welcome_item9' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'psCustomerGroup',
'page' => 'list' ),
'welcome_item10' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'psEmployeeGroup',
'page' => 'list' ),
'welcome_item11' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'psProductGroup',
'page' => 'list' ),
'welcome_item12' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'psSupplierGroup',
'page' => 'list' ),
'welcome_item13' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'psUnits',
'page' => 'list' ),
'welcome_item14' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'psUserGroup',
'page' => 'list' ),
'welcome_item17' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'umUserInfo',
'page' => 'list' ),
'welcome_item15' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'tSaleH',
'page' => 'list' ),
'welcome_item16' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'tSaleD',
'page' => 'list' ),
'welcome_item18' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'karsaaz_posugrights',
'page' => 'list' ),
'welcome_item19' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'karsaaz_posugmembers',
'page' => 'list' ),
'welcome_item20' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'karsaaz_posuggroups',
'page' => 'list' ),
'welcome_item21' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'pBU',
'page' => 'list' ),
'welcome_item22' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'AccountCBal',
'page' => 'list' ),
'welcome_item23' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'pBank',
'page' => 'list' ),
'welcome_item24' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'psBankGroup',
'page' => 'list' ),
'welcome_item25' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'sClosingMonth',
'page' => 'list' ),
'welcome_item26' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'comission_group',
'page' => 'list' ),
'welcome_item27' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'comission_group_detail',
'page' => 'list' ),
'welcome_item28' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'label_codes',
'page' => 'list' ),
'welcome_item29' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'label_groups',
'page' => 'list' ),
'welcome_item30' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'language_lael',
'page' => 'list' ),
'welcome_item31' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'languages',
'page' => 'list' ),
'welcome_item32' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'selected_lanugage',
'page' => 'list' ) ) ),
'fields' => array( 'gridFields' => array(  ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array(  ) ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'above-grid' => array(  ),
'supertop' => array( 'expand_menu_button',
'collapse_button',
'menu',
'loginform_login',
'username_button' ),
'left' => array( 'logo',
'expand_button' ),
'grid' => array( 'welcome_item',
'welcome_item1',
'welcome_item2',
'welcome_item3',
'welcome_item4',
'welcome_item5',
'welcome_item7',
'welcome_item6',
'welcome_item8',
'welcome_item9',
'welcome_item10',
'welcome_item11',
'welcome_item12',
'welcome_item13',
'welcome_item14',
'welcome_item17',
'welcome_item15',
'welcome_item16',
'welcome_item18',
'welcome_item19',
'welcome_item20',
'welcome_item21',
'welcome_item22',
'welcome_item23',
'welcome_item24',
'welcome_item25',
'welcome_item26',
'welcome_item27',
'welcome_item28',
'welcome_item29',
'welcome_item30',
'welcome_item31',
'welcome_item32' ) ),
'formXtTags' => array( 'above-grid' => array(  ) ),
'itemForms' => array( 'expand_menu_button' => 'supertop',
'collapse_button' => 'supertop',
'menu' => 'supertop',
'loginform_login' => 'supertop',
'username_button' => 'supertop',
'logo' => 'left',
'expand_button' => 'left',
'welcome_item' => 'grid',
'welcome_item1' => 'grid',
'welcome_item2' => 'grid',
'welcome_item3' => 'grid',
'welcome_item4' => 'grid',
'welcome_item5' => 'grid',
'welcome_item7' => 'grid',
'welcome_item6' => 'grid',
'welcome_item8' => 'grid',
'welcome_item9' => 'grid',
'welcome_item10' => 'grid',
'welcome_item11' => 'grid',
'welcome_item12' => 'grid',
'welcome_item13' => 'grid',
'welcome_item14' => 'grid',
'welcome_item17' => 'grid',
'welcome_item15' => 'grid',
'welcome_item16' => 'grid',
'welcome_item18' => 'grid',
'welcome_item19' => 'grid',
'welcome_item20' => 'grid',
'welcome_item21' => 'grid',
'welcome_item22' => 'grid',
'welcome_item23' => 'grid',
'welcome_item24' => 'grid',
'welcome_item25' => 'grid',
'welcome_item26' => 'grid',
'welcome_item27' => 'grid',
'welcome_item28' => 'grid',
'welcome_item29' => 'grid',
'welcome_item30' => 'grid',
'welcome_item31' => 'grid',
'welcome_item32' => 'grid' ),
'itemLocations' => array(  ),
'itemVisiblity' => array( 'expand_menu_button' => 2,
'expand_button' => 5 ) ),
'itemsByType' => array( 'welcome_item' => array( 'welcome_item',
'welcome_item1',
'welcome_item2',
'welcome_item3',
'welcome_item4',
'welcome_item5',
'welcome_item7',
'welcome_item6',
'welcome_item8',
'welcome_item9',
'welcome_item10',
'welcome_item11',
'welcome_item12',
'welcome_item13',
'welcome_item14',
'welcome_item15',
'welcome_item16',
'welcome_item17',
'welcome_item18',
'welcome_item19',
'welcome_item20',
'welcome_item21',
'welcome_item22',
'welcome_item23',
'welcome_item24',
'welcome_item25',
'welcome_item26',
'welcome_item27',
'welcome_item28',
'welcome_item29',
'welcome_item30',
'welcome_item31',
'welcome_item32' ),
'userinfo_link' => array( 'userinfo_link' ),
'logout_link' => array( 'logout_link' ),
'logo' => array( 'logo' ),
'menu' => array( 'menu' ),
'username_button' => array( 'username_button' ),
'loginform_login' => array( 'loginform_login' ),
'expand_menu_button' => array( 'expand_menu_button' ),
'collapse_button' => array( 'collapse_button' ),
'adminarea_link' => array( 'adminarea_link' ),
'expand_button' => array( 'expand_button' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 0 ),
'page' => array( 'verticalBar' => true,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'menu',
'type' => 'menu',
'layoutId' => 'twomenu',
'disabled' => 0,
'default' => 0,
'forms' => array( 'above-grid' => array( 'modelId' => 'empty-above-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'supertop' => array( 'modelId' => 'menu2-topbar',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'expand_menu_button',
'collapse_button',
'menu' ) ),
'c2' => array( 'model' => 'c2',
'items' => array( 'loginform_login',
'username_button' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'left' => array( 'modelId' => 'leftbar2-menu',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c0' ) ),
'section' => '' ) ),
'cells' => array( 'c0' => array( 'model' => 'c0',
'items' => array( 'logo',
'expand_button' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'welcome',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'welcome_item',
'welcome_item1',
'welcome_item2',
'welcome_item3',
'welcome_item4',
'welcome_item5',
'welcome_item7',
'welcome_item6',
'welcome_item8',
'welcome_item9',
'welcome_item10',
'welcome_item11',
'welcome_item12',
'welcome_item13',
'welcome_item14',
'welcome_item17',
'welcome_item15',
'welcome_item16',
'welcome_item18',
'welcome_item19',
'welcome_item20',
'welcome_item21',
'welcome_item22',
'welcome_item23',
'welcome_item24',
'welcome_item25',
'welcome_item26',
'welcome_item27',
'welcome_item28',
'welcome_item29',
'welcome_item30',
'welcome_item31',
'welcome_item32' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'welcome_item' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'GLTD',
'linkPage' => 'list',
'linkText' => array( 'table' => 'GLTD',
'type' => 6 ),
'linkIcon' => array( 'glyph' => 'calendar' ),
'linkComments' => array( 'text' => 'GLTD description',
'type' => 0 ),
'background' => '#E67349',
'linkType' => 0 ),
'welcome_item1' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'GltH',
'linkPage' => 'list',
'linkText' => array( 'table' => 'GltH',
'type' => 6 ),
'linkIcon' => array( 'glyph' => 'tree-conifer' ),
'linkComments' => array( 'text' => 'Glt H description',
'type' => 0 ),
'background' => '#7B68EE',
'linkType' => 0 ),
'welcome_item2' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'pAccounts',
'linkPage' => 'list',
'linkText' => array( 'table' => 'pAccounts',
'type' => 6 ),
'linkIcon' => array( 'glyph' => 'camera' ),
'linkComments' => array( 'text' => 'P Accounts description',
'type' => 0 ),
'background' => '#CD5C5C',
'linkType' => 0 ),
'welcome_item3' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'pCustomer',
'linkPage' => 'list',
'linkText' => array( 'table' => 'pCustomer',
'type' => 6 ),
'linkIcon' => array( 'glyph' => 'barcode' ),
'linkComments' => array( 'text' => 'P Customer description',
'type' => 0 ),
'background' => '#4169E1',
'linkType' => 0 ),
'welcome_item4' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'pEmployee',
'linkPage' => 'list',
'linkText' => array( 'table' => 'pEmployee',
'type' => 6 ),
'linkIcon' => array( 'glyph' => 'earphone' ),
'linkComments' => array( 'text' => 'P Employee description',
'type' => 0 ),
'background' => '#778899',
'linkType' => 0 ),
'welcome_item5' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'pProductItems',
'linkPage' => 'list',
'linkText' => array( 'table' => 'pProductItems',
'type' => 6 ),
'linkIcon' => array( 'glyph' => 'fire' ),
'background' => '#008B8B',
'linkType' => 0 ),
'welcome_item7' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'pSupplier',
'linkPage' => 'list',
'linkText' => array( 'table' => 'pSupplier',
'type' => 6 ),
'background' => '#E8926F',
'linkType' => 0 ),
'welcome_item6' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'psAccountSubGroup',
'linkPage' => 'list',
'linkText' => array( 'table' => 'psAccountSubGroup',
'type' => 6 ),
'background' => '#2F4F4F',
'linkType' => 0 ),
'welcome_item8' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'psChartofAccounts',
'linkPage' => 'list',
'linkText' => array( 'table' => 'psChartofAccounts',
'type' => 6 ),
'background' => '#4682B4',
'linkType' => 0 ),
'welcome_item9' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'psCustomerGroup',
'linkPage' => 'list',
'linkText' => array( 'table' => 'psCustomerGroup',
'type' => 6 ),
'background' => '#4169E1',
'linkType' => 0 ),
'welcome_item10' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'psEmployeeGroup',
'linkPage' => 'list',
'linkText' => array( 'table' => 'psEmployeeGroup',
'type' => 6 ),
'background' => '#2F4F4F',
'linkType' => 0 ),
'welcome_item11' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'psProductGroup',
'linkPage' => 'list',
'linkText' => array( 'table' => 'psProductGroup',
'type' => 6 ),
'background' => '#8FBC8B',
'linkType' => 0 ),
'welcome_item12' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'psSupplierGroup',
'linkPage' => 'list',
'linkText' => array( 'table' => 'psSupplierGroup',
'type' => 6 ),
'background' => '#EDCA00',
'linkType' => 0 ),
'welcome_item13' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'psUnits',
'linkPage' => 'list',
'linkText' => array( 'table' => 'psUnits',
'type' => 6 ),
'background' => '#CFAE83',
'linkType' => 0 ),
'welcome_item14' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'psUserGroup',
'linkPage' => 'list',
'linkText' => array( 'table' => 'psUserGroup',
'type' => 6 ),
'background' => '#EDCA00',
'linkType' => 0 ),
'welcome_item15' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'tSaleH',
'linkPage' => 'list',
'linkText' => array( 'table' => 'tSaleH',
'type' => 6 ),
'background' => '#B22222',
'linkType' => 0 ),
'welcome_item16' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'tSaleD',
'linkPage' => 'list',
'linkText' => array( 'table' => 'tSaleD',
'type' => 6 ),
'background' => '#00C2C5',
'linkType' => 0 ),
'welcome_item17' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'umUserInfo',
'linkPage' => 'list',
'linkText' => array( 'table' => 'umUserInfo',
'type' => 6 ),
'background' => '#6493EA',
'linkType' => 0 ),
'userinfo_link' => array( 'type' => 'userinfo_link' ),
'logout_link' => array( 'type' => 'logout_link' ),
'logo' => array( 'type' => 'logo' ),
'menu' => array( 'type' => 'menu' ),
'username_button' => array( 'type' => 'username_button',
'items' => array( 'userinfo_link',
'logout_link',
'adminarea_link' ) ),
'loginform_login' => array( 'type' => 'loginform_login',
'popup' => false ),
'expand_menu_button' => array( 'type' => 'expand_menu_button' ),
'collapse_button' => array( 'type' => 'collapse_button' ),
'adminarea_link' => array( 'type' => 'adminarea_link' ),
'welcome_item18' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'karsaaz_posugrights',
'linkPage' => 'list',
'linkText' => array( 'table' => 'karsaaz_posugrights',
'type' => 6 ),
'background' => '#4682B4',
'linkType' => 0 ),
'welcome_item19' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'karsaaz_posugmembers',
'linkPage' => 'list',
'linkText' => array( 'table' => 'karsaaz_posugmembers',
'type' => 6 ),
'background' => '#5F9EA0',
'linkType' => 0 ),
'welcome_item20' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'karsaaz_posuggroups',
'linkPage' => 'list',
'linkText' => array( 'table' => 'karsaaz_posuggroups',
'type' => 6 ),
'background' => '#E67349',
'linkType' => 0 ),
'welcome_item21' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'pBU',
'linkPage' => 'list',
'linkText' => array( 'table' => 'pBU',
'type' => 6 ),
'background' => '#4169E1',
'linkType' => 0 ),
'welcome_item22' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'AccountCBal',
'linkPage' => 'list',
'linkText' => array( 'table' => 'AccountCBal',
'type' => 6 ),
'background' => '#E67349',
'linkType' => 0 ),
'welcome_item23' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'pBank',
'linkPage' => 'list',
'linkText' => array( 'table' => 'pBank',
'type' => 6 ),
'background' => '#4169E1',
'linkType' => 0 ),
'welcome_item24' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'psBankGroup',
'linkPage' => 'list',
'linkText' => array( 'table' => 'psBankGroup',
'type' => 6 ),
'background' => '#2F4F4F',
'linkType' => 0 ),
'welcome_item25' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'sClosingMonth',
'linkPage' => 'list',
'linkText' => array( 'table' => 'sClosingMonth',
'type' => 6 ),
'background' => '#BC8F8F',
'linkType' => 0 ),
'welcome_item26' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'comission_group',
'linkPage' => 'list',
'linkText' => array( 'table' => 'comission_group',
'type' => 6 ),
'background' => '#8FBC8B',
'linkType' => 0 ),
'welcome_item27' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'comission_group_detail',
'linkPage' => 'list',
'linkText' => array( 'table' => 'comission_group_detail',
'type' => 6 ),
'background' => '#E8926F',
'linkType' => 0 ),
'welcome_item28' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'label_codes',
'linkPage' => 'list',
'linkText' => array( 'table' => 'label_codes',
'type' => 6 ),
'background' => '#00C2C5',
'linkType' => 0 ),
'welcome_item29' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'label_groups',
'linkPage' => 'list',
'linkText' => array( 'table' => 'label_groups',
'type' => 6 ),
'background' => '#008B8B',
'linkType' => 0 ),
'welcome_item30' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'language_lael',
'linkPage' => 'list',
'linkText' => array( 'table' => 'language_lael',
'type' => 6 ),
'background' => '#E8926F',
'linkType' => 0 ),
'welcome_item31' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'languages',
'linkPage' => 'list',
'linkText' => array( 'table' => 'languages',
'type' => 6 ),
'background' => '#E8926F',
'linkType' => 0 ),
'welcome_item32' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'selected_lanugage',
'linkPage' => 'list',
'linkText' => array( 'table' => 'selected_lanugage',
'type' => 6 ),
'background' => '#00C2C5',
'linkType' => 0 ),
'expand_button' => array( 'type' => 'expand_button' ) ),
'dbProps' => array(  ),
'version' => 11,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right' );
		?>