<?php
			$optionsArray = array( 'totals' => array( 'Code' => array( 'totalsType' => '' ),
'ParentAccountCode' => array( 'totalsType' => '' ),
'ParentCode' => array( 'totalsType' => '' ),
'AccountCode' => array( 'totalsType' => '' ),
'BuCode' => array( 'totalsType' => '' ),
'AccountTypeCode' => array( 'totalsType' => '' ),
'AccountType' => array( 'totalsType' => '' ),
'CBalance' => array( 'totalsType' => '' ),
'CBalStatus' => array( 'totalsType' => '' ),
'FcCBalance' => array( 'totalsType' => '' ),
'FCBalStatus' => array( 'totalsType' => '' ),
'Remarks' => array( 'totalsType' => '' ),
'FcCurrencyCode' => array( 'totalsType' => '' ),
'AccStatusType' => array( 'totalsType' => '' ),
'UDate' => array( 'totalsType' => '' ) ),
'fields' => array( 'gridFields' => array( 'Code',
'ParentAccountCode',
'ParentCode',
'AccountCode',
'BuCode',
'AccountTypeCode',
'AccountType',
'CBalance',
'CBalStatus',
'FcCBalance',
'FCBalStatus',
'Remarks',
'FcCurrencyCode',
'AccStatusType',
'UDate' ),
'exportFields' => array( 'Code',
'ParentAccountCode',
'ParentCode',
'AccountCode',
'BuCode',
'AccountTypeCode',
'AccountType',
'CBalance',
'CBalStatus',
'FcCBalance',
'FCBalStatus',
'Remarks',
'FcCurrencyCode',
'AccStatusType',
'UDate' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'Code' => array( 'export_field' ),
'ParentAccountCode' => array( 'export_field1' ),
'ParentCode' => array( 'export_field2' ),
'AccountCode' => array( 'export_field3' ),
'BuCode' => array( 'export_field4' ),
'AccountTypeCode' => array( 'export_field5' ),
'AccountType' => array( 'export_field6' ),
'CBalance' => array( 'export_field7' ),
'CBalStatus' => array( 'export_field8' ),
'FcCBalance' => array( 'export_field9' ),
'FCBalStatus' => array( 'export_field10' ),
'Remarks' => array( 'export_field11' ),
'FcCurrencyCode' => array( 'export_field12' ),
'AccStatusType' => array( 'export_field13' ),
'UDate' => array( 'export_field14' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'export_header' ),
'grid' => array( 'export_field',
'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field14' ),
'footer' => array( 'export_export',
'export_cancel' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'export_header' => 'top',
'export_field' => 'grid',
'export_field1' => 'grid',
'export_field2' => 'grid',
'export_field3' => 'grid',
'export_field4' => 'grid',
'export_field5' => 'grid',
'export_field6' => 'grid',
'export_field7' => 'grid',
'export_field8' => 'grid',
'export_field9' => 'grid',
'export_field10' => 'grid',
'export_field11' => 'grid',
'export_field12' => 'grid',
'export_field13' => 'grid',
'export_field14' => 'grid',
'export_export' => 'footer',
'export_cancel' => 'footer' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'export_header' => array( 'export_header' ),
'export_export' => array( 'export_export' ),
'export_cancel' => array( 'export_cancel' ),
'export_field' => array( 'export_field',
'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field14' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'export' => array( 'format' => 2,
'selectFields' => false,
'delimiter' => ',',
'selectDelimiter' => false,
'exportFileTypes' => array( 'excel' => true,
'word' => true,
'csv' => true,
'xml' => false ) ) );
			$pageArray = array( 'id' => 'export',
'type' => 'export',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'export-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_header' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'export-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_field',
'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field14' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'footer' => array( 'modelId' => 'export-footer',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ),
'c2' => array( 'model' => 'c2',
'items' => array( 'export_export',
'export_cancel' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'export_header' => array( 'type' => 'export_header' ),
'export_export' => array( 'type' => 'export_export' ),
'export_cancel' => array( 'type' => 'export_cancel' ),
'export_field' => array( 'field' => 'Code',
'type' => 'export_field' ),
'export_field1' => array( 'field' => 'ParentAccountCode',
'type' => 'export_field' ),
'export_field2' => array( 'field' => 'ParentCode',
'type' => 'export_field' ),
'export_field3' => array( 'field' => 'AccountCode',
'type' => 'export_field' ),
'export_field4' => array( 'field' => 'BuCode',
'type' => 'export_field' ),
'export_field5' => array( 'field' => 'AccountTypeCode',
'type' => 'export_field' ),
'export_field6' => array( 'field' => 'AccountType',
'type' => 'export_field' ),
'export_field7' => array( 'field' => 'CBalance',
'type' => 'export_field' ),
'export_field8' => array( 'field' => 'CBalStatus',
'type' => 'export_field' ),
'export_field9' => array( 'field' => 'FcCBalance',
'type' => 'export_field' ),
'export_field10' => array( 'field' => 'FCBalStatus',
'type' => 'export_field' ),
'export_field11' => array( 'field' => 'Remarks',
'type' => 'export_field' ),
'export_field12' => array( 'field' => 'FcCurrencyCode',
'type' => 'export_field' ),
'export_field13' => array( 'field' => 'AccStatusType',
'type' => 'export_field' ),
'export_field14' => array( 'field' => 'UDate',
'type' => 'export_field' ) ),
'dbProps' => array(  ),
'version' => 11,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'exportFormat' => 2,
'exportDelimiter' => ',',
'exportSelectDelimiter' => false,
'exportSelectFields' => false );
		?>