<?php
			$optionsArray = array( 'totals' => array( 'Code' => array( 'totalsType' => '' ),
'UserName' => array( 'totalsType' => '' ),
'CellNo' => array( 'totalsType' => '' ),
'Email' => array( 'totalsType' => '' ),
'LoginUserName' => array( 'totalsType' => '' ),
'Password' => array( 'totalsType' => '' ),
'PasswordHint' => array( 'totalsType' => '' ),
'GroupCode' => array( 'totalsType' => '' ),
'Remarks' => array( 'totalsType' => '' ),
'UserType' => array( 'totalsType' => '' ),
'isAccountActive' => array( 'totalsType' => '' ),
'NoOfAttempt' => array( 'totalsType' => '' ),
'NoOfWorngAttempt' => array( 'totalsType' => '' ),
'api_key' => array( 'totalsType' => '' ) ),
'fields' => array( 'gridFields' => array( 'Code',
'UserName',
'CellNo',
'Email',
'LoginUserName',
'Password',
'PasswordHint',
'GroupCode',
'Remarks',
'UserType',
'isAccountActive',
'NoOfAttempt',
'NoOfWorngAttempt',
'api_key' ),
'exportFields' => array( 'Code',
'UserName',
'CellNo',
'Email',
'LoginUserName',
'Password',
'PasswordHint',
'GroupCode',
'Remarks',
'UserType',
'isAccountActive',
'NoOfAttempt',
'NoOfWorngAttempt',
'api_key' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'Code' => array( 'export_field' ),
'UserName' => array( 'export_field1' ),
'CellNo' => array( 'export_field2' ),
'Email' => array( 'export_field3' ),
'LoginUserName' => array( 'export_field4' ),
'Password' => array( 'export_field5' ),
'PasswordHint' => array( 'export_field6' ),
'GroupCode' => array( 'export_field7' ),
'Remarks' => array( 'export_field8' ),
'UserType' => array( 'export_field9' ),
'isAccountActive' => array( 'export_field10' ),
'NoOfAttempt' => array( 'export_field11' ),
'NoOfWorngAttempt' => array( 'export_field12' ),
'api_key' => array( 'export_field13' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'export_header' ),
'grid' => array( 'export_field',
'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13' ),
'footer' => array( 'export_export',
'export_cancel' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'export_header' => 'top',
'export_field' => 'grid',
'export_field1' => 'grid',
'export_field2' => 'grid',
'export_field3' => 'grid',
'export_field4' => 'grid',
'export_field5' => 'grid',
'export_field6' => 'grid',
'export_field7' => 'grid',
'export_field8' => 'grid',
'export_field9' => 'grid',
'export_field10' => 'grid',
'export_field11' => 'grid',
'export_field12' => 'grid',
'export_field13' => 'grid',
'export_export' => 'footer',
'export_cancel' => 'footer' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'export_header' => array( 'export_header' ),
'export_export' => array( 'export_export' ),
'export_cancel' => array( 'export_cancel' ),
'export_field' => array( 'export_field',
'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'export' => array( 'format' => 2,
'selectFields' => false,
'delimiter' => ',',
'selectDelimiter' => false,
'exportFileTypes' => array( 'excel' => true,
'word' => true,
'csv' => true,
'xml' => false ) ) );
			$pageArray = array( 'id' => 'export',
'type' => 'export',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'export-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_header' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'export-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_field',
'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'footer' => array( 'modelId' => 'export-footer',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ),
'c2' => array( 'model' => 'c2',
'items' => array( 'export_export',
'export_cancel' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'export_header' => array( 'type' => 'export_header' ),
'export_export' => array( 'type' => 'export_export' ),
'export_cancel' => array( 'type' => 'export_cancel' ),
'export_field' => array( 'field' => 'Code',
'type' => 'export_field' ),
'export_field1' => array( 'field' => 'UserName',
'type' => 'export_field' ),
'export_field2' => array( 'field' => 'CellNo',
'type' => 'export_field' ),
'export_field3' => array( 'field' => 'Email',
'type' => 'export_field' ),
'export_field4' => array( 'field' => 'LoginUserName',
'type' => 'export_field' ),
'export_field5' => array( 'field' => 'Password',
'type' => 'export_field' ),
'export_field6' => array( 'field' => 'PasswordHint',
'type' => 'export_field' ),
'export_field7' => array( 'field' => 'GroupCode',
'type' => 'export_field' ),
'export_field8' => array( 'field' => 'Remarks',
'type' => 'export_field' ),
'export_field9' => array( 'field' => 'UserType',
'type' => 'export_field' ),
'export_field10' => array( 'field' => 'isAccountActive',
'type' => 'export_field' ),
'export_field11' => array( 'field' => 'NoOfAttempt',
'type' => 'export_field' ),
'export_field12' => array( 'field' => 'NoOfWorngAttempt',
'type' => 'export_field' ),
'export_field13' => array( 'field' => 'api_key',
'type' => 'export_field' ) ),
'dbProps' => array(  ),
'version' => 11,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'exportFormat' => 2,
'exportDelimiter' => ',',
'exportSelectDelimiter' => false,
'exportSelectFields' => false );
		?>