<?php
			$optionsArray = array( 'fields' => array( 'gridFields' => array( 'Code',
'BookCode',
'VirtualCode',
'TBook',
'TType',
'TDate',
'BUnit',
'Status',
'Remarks',
'UserName',
'CreateDate',
'CreateTime',
'UpdateUser',
'UpdateDate',
'UpdateTime',
'Block',
'Lock',
'TotalAmount' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'Code' => array( 'import_field' ),
'BookCode' => array( 'import_field1' ),
'VirtualCode' => array( 'import_field2' ),
'TBook' => array( 'import_field3' ),
'TType' => array( 'import_field4' ),
'TDate' => array( 'import_field5' ),
'BUnit' => array( 'import_field6' ),
'Status' => array( 'import_field7' ),
'Remarks' => array( 'import_field8' ),
'UserName' => array( 'import_field9' ),
'CreateDate' => array( 'import_field10' ),
'CreateTime' => array( 'import_field11' ),
'UpdateUser' => array( 'import_field12' ),
'UpdateDate' => array( 'import_field13' ),
'UpdateTime' => array( 'import_field14' ),
'Block' => array( 'import_field15' ),
'Lock' => array( 'import_field16' ),
'TotalAmount' => array( 'import_field17' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'import_header' ),
'grid' => array( 'import_field',
'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12',
'import_field13',
'import_field14',
'import_field15',
'import_field16',
'import_field17' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'import_header' => 'top',
'import_field' => 'grid',
'import_field1' => 'grid',
'import_field2' => 'grid',
'import_field3' => 'grid',
'import_field4' => 'grid',
'import_field5' => 'grid',
'import_field6' => 'grid',
'import_field7' => 'grid',
'import_field8' => 'grid',
'import_field9' => 'grid',
'import_field10' => 'grid',
'import_field11' => 'grid',
'import_field12' => 'grid',
'import_field13' => 'grid',
'import_field14' => 'grid',
'import_field15' => 'grid',
'import_field16' => 'grid',
'import_field17' => 'grid' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'import_header' => array( 'import_header' ),
'import_field' => array( 'import_field',
'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12',
'import_field13',
'import_field14',
'import_field15',
'import_field16',
'import_field17' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'import',
'type' => 'import',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'import-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_header' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'import-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_field',
'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12',
'import_field13',
'import_field14',
'import_field15',
'import_field16',
'import_field17' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'import_header' => array( 'type' => 'import_header' ),
'import_field' => array( 'field' => 'Code',
'type' => 'import_field' ),
'import_field1' => array( 'field' => 'BookCode',
'type' => 'import_field' ),
'import_field2' => array( 'field' => 'VirtualCode',
'type' => 'import_field' ),
'import_field3' => array( 'field' => 'TBook',
'type' => 'import_field' ),
'import_field4' => array( 'field' => 'TType',
'type' => 'import_field' ),
'import_field5' => array( 'field' => 'TDate',
'type' => 'import_field' ),
'import_field6' => array( 'field' => 'BUnit',
'type' => 'import_field' ),
'import_field7' => array( 'field' => 'Status',
'type' => 'import_field' ),
'import_field8' => array( 'field' => 'Remarks',
'type' => 'import_field' ),
'import_field9' => array( 'field' => 'UserName',
'type' => 'import_field' ),
'import_field10' => array( 'field' => 'CreateDate',
'type' => 'import_field' ),
'import_field11' => array( 'field' => 'CreateTime',
'type' => 'import_field' ),
'import_field12' => array( 'field' => 'UpdateUser',
'type' => 'import_field' ),
'import_field13' => array( 'field' => 'UpdateDate',
'type' => 'import_field' ),
'import_field14' => array( 'field' => 'UpdateTime',
'type' => 'import_field' ),
'import_field15' => array( 'field' => 'Block',
'type' => 'import_field' ),
'import_field16' => array( 'field' => 'Lock',
'type' => 'import_field' ),
'import_field17' => array( 'field' => 'TotalAmount',
'type' => 'import_field' ) ),
'dbProps' => array(  ),
'version' => 11,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right' );
		?>