<?php
			$optionsArray = array( 'fields' => array( 'gridFields' => array( 'ID',
'Code',
'TMonth',
'TYear',
'BookCode',
'BookID',
'VirtualCode',
'TBook',
'TType',
'TDate',
'BUnit',
'Status',
'PartyCode',
'TotalAmount',
'FreightAccountCode',
'FreightCharges',
'LaborAccountCode',
'LaborCharges',
'SaleTaxAccCode',
'SaleTaxRate',
'SaleTaxAmount',
'DiscountAccCode',
'DiscountRemarks',
'DiscountRate',
'DiscountAmount',
'GrandTotal',
'SaleMenCode',
'Commission',
'Remarks',
'UserName',
'CreateDate',
'CreateTime',
'UpdateUser',
'UpdateDate',
'UpdateTime',
'Block' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'ID' => array( 'import_field' ),
'Code' => array( 'import_field1' ),
'TMonth' => array( 'import_field2' ),
'TYear' => array( 'import_field3' ),
'BookCode' => array( 'import_field4' ),
'BookID' => array( 'import_field5' ),
'VirtualCode' => array( 'import_field6' ),
'TBook' => array( 'import_field7' ),
'TType' => array( 'import_field8' ),
'TDate' => array( 'import_field9' ),
'BUnit' => array( 'import_field10' ),
'Status' => array( 'import_field11' ),
'PartyCode' => array( 'import_field12' ),
'TotalAmount' => array( 'import_field13' ),
'FreightAccountCode' => array( 'import_field14' ),
'FreightCharges' => array( 'import_field15' ),
'LaborAccountCode' => array( 'import_field16' ),
'LaborCharges' => array( 'import_field17' ),
'SaleTaxAccCode' => array( 'import_field18' ),
'SaleTaxRate' => array( 'import_field19' ),
'SaleTaxAmount' => array( 'import_field20' ),
'DiscountAccCode' => array( 'import_field21' ),
'DiscountRemarks' => array( 'import_field22' ),
'DiscountRate' => array( 'import_field23' ),
'DiscountAmount' => array( 'import_field24' ),
'GrandTotal' => array( 'import_field25' ),
'SaleMenCode' => array( 'import_field26' ),
'Commission' => array( 'import_field27' ),
'Remarks' => array( 'import_field28' ),
'UserName' => array( 'import_field29' ),
'CreateDate' => array( 'import_field30' ),
'CreateTime' => array( 'import_field31' ),
'UpdateUser' => array( 'import_field32' ),
'UpdateDate' => array( 'import_field33' ),
'UpdateTime' => array( 'import_field34' ),
'Block' => array( 'import_field35' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'import_header' ),
'grid' => array( 'import_field',
'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12',
'import_field13',
'import_field14',
'import_field15',
'import_field16',
'import_field17',
'import_field18',
'import_field19',
'import_field20',
'import_field21',
'import_field22',
'import_field23',
'import_field24',
'import_field25',
'import_field26',
'import_field27',
'import_field28',
'import_field29',
'import_field30',
'import_field31',
'import_field32',
'import_field33',
'import_field34',
'import_field35' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'import_header' => 'top',
'import_field' => 'grid',
'import_field1' => 'grid',
'import_field2' => 'grid',
'import_field3' => 'grid',
'import_field4' => 'grid',
'import_field5' => 'grid',
'import_field6' => 'grid',
'import_field7' => 'grid',
'import_field8' => 'grid',
'import_field9' => 'grid',
'import_field10' => 'grid',
'import_field11' => 'grid',
'import_field12' => 'grid',
'import_field13' => 'grid',
'import_field14' => 'grid',
'import_field15' => 'grid',
'import_field16' => 'grid',
'import_field17' => 'grid',
'import_field18' => 'grid',
'import_field19' => 'grid',
'import_field20' => 'grid',
'import_field21' => 'grid',
'import_field22' => 'grid',
'import_field23' => 'grid',
'import_field24' => 'grid',
'import_field25' => 'grid',
'import_field26' => 'grid',
'import_field27' => 'grid',
'import_field28' => 'grid',
'import_field29' => 'grid',
'import_field30' => 'grid',
'import_field31' => 'grid',
'import_field32' => 'grid',
'import_field33' => 'grid',
'import_field34' => 'grid',
'import_field35' => 'grid' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'import_header' => array( 'import_header' ),
'import_field' => array( 'import_field',
'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12',
'import_field13',
'import_field14',
'import_field15',
'import_field16',
'import_field17',
'import_field18',
'import_field19',
'import_field20',
'import_field21',
'import_field22',
'import_field23',
'import_field24',
'import_field25',
'import_field26',
'import_field27',
'import_field28',
'import_field29',
'import_field30',
'import_field31',
'import_field32',
'import_field33',
'import_field34',
'import_field35' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'import',
'type' => 'import',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'import-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_header' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'import-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_field',
'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12',
'import_field13',
'import_field14',
'import_field15',
'import_field16',
'import_field17',
'import_field18',
'import_field19',
'import_field20',
'import_field21',
'import_field22',
'import_field23',
'import_field24',
'import_field25',
'import_field26',
'import_field27',
'import_field28',
'import_field29',
'import_field30',
'import_field31',
'import_field32',
'import_field33',
'import_field34',
'import_field35' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'import_header' => array( 'type' => 'import_header' ),
'import_field' => array( 'field' => 'ID',
'type' => 'import_field' ),
'import_field1' => array( 'field' => 'Code',
'type' => 'import_field' ),
'import_field2' => array( 'field' => 'TMonth',
'type' => 'import_field' ),
'import_field3' => array( 'field' => 'TYear',
'type' => 'import_field' ),
'import_field4' => array( 'field' => 'BookCode',
'type' => 'import_field' ),
'import_field5' => array( 'field' => 'BookID',
'type' => 'import_field' ),
'import_field6' => array( 'field' => 'VirtualCode',
'type' => 'import_field' ),
'import_field7' => array( 'field' => 'TBook',
'type' => 'import_field' ),
'import_field8' => array( 'field' => 'TType',
'type' => 'import_field' ),
'import_field9' => array( 'field' => 'TDate',
'type' => 'import_field' ),
'import_field10' => array( 'field' => 'BUnit',
'type' => 'import_field' ),
'import_field11' => array( 'field' => 'Status',
'type' => 'import_field' ),
'import_field12' => array( 'field' => 'PartyCode',
'type' => 'import_field' ),
'import_field13' => array( 'field' => 'TotalAmount',
'type' => 'import_field' ),
'import_field14' => array( 'field' => 'FreightAccountCode',
'type' => 'import_field' ),
'import_field15' => array( 'field' => 'FreightCharges',
'type' => 'import_field' ),
'import_field16' => array( 'field' => 'LaborAccountCode',
'type' => 'import_field' ),
'import_field17' => array( 'field' => 'LaborCharges',
'type' => 'import_field' ),
'import_field18' => array( 'field' => 'SaleTaxAccCode',
'type' => 'import_field' ),
'import_field19' => array( 'field' => 'SaleTaxRate',
'type' => 'import_field' ),
'import_field20' => array( 'field' => 'SaleTaxAmount',
'type' => 'import_field' ),
'import_field21' => array( 'field' => 'DiscountAccCode',
'type' => 'import_field' ),
'import_field22' => array( 'field' => 'DiscountRemarks',
'type' => 'import_field' ),
'import_field23' => array( 'field' => 'DiscountRate',
'type' => 'import_field' ),
'import_field24' => array( 'field' => 'DiscountAmount',
'type' => 'import_field' ),
'import_field25' => array( 'field' => 'GrandTotal',
'type' => 'import_field' ),
'import_field26' => array( 'field' => 'SaleMenCode',
'type' => 'import_field' ),
'import_field27' => array( 'field' => 'Commission',
'type' => 'import_field' ),
'import_field28' => array( 'field' => 'Remarks',
'type' => 'import_field' ),
'import_field29' => array( 'field' => 'UserName',
'type' => 'import_field' ),
'import_field30' => array( 'field' => 'CreateDate',
'type' => 'import_field' ),
'import_field31' => array( 'field' => 'CreateTime',
'type' => 'import_field' ),
'import_field32' => array( 'field' => 'UpdateUser',
'type' => 'import_field' ),
'import_field33' => array( 'field' => 'UpdateDate',
'type' => 'import_field' ),
'import_field34' => array( 'field' => 'UpdateTime',
'type' => 'import_field' ),
'import_field35' => array( 'field' => 'Block',
'type' => 'import_field' ) ),
'dbProps' => array(  ),
'version' => 11,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right' );
		?>