<?php
			$optionsArray = array( 'fields' => array( 'gridFields' => array( 'Code',
'CodeD',
'VirtualCode',
'Tdate',
'Status',
'PartyCode',
'StoreCode',
'ProductCode',
'ProductGroupCode',
'UnitCode',
'Qty',
'Rate',
'Amount',
'Remarks',
'UserName',
'CreateDate',
'CreateTime',
'UpdateUser',
'UpdateDate',
'UpdateTime',
'Block',
'BuCode',
'TotalNos' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'Code' => array( 'import_field' ),
'CodeD' => array( 'import_field1' ),
'VirtualCode' => array( 'import_field2' ),
'Tdate' => array( 'import_field3' ),
'Status' => array( 'import_field4' ),
'PartyCode' => array( 'import_field5' ),
'StoreCode' => array( 'import_field6' ),
'ProductCode' => array( 'import_field7' ),
'ProductGroupCode' => array( 'import_field8' ),
'UnitCode' => array( 'import_field9' ),
'Qty' => array( 'import_field10' ),
'Rate' => array( 'import_field11' ),
'Amount' => array( 'import_field12' ),
'Remarks' => array( 'import_field13' ),
'UserName' => array( 'import_field14' ),
'CreateDate' => array( 'import_field15' ),
'CreateTime' => array( 'import_field16' ),
'UpdateUser' => array( 'import_field17' ),
'UpdateDate' => array( 'import_field18' ),
'UpdateTime' => array( 'import_field19' ),
'Block' => array( 'import_field20' ),
'BuCode' => array( 'import_field21' ),
'TotalNos' => array( 'import_field22' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'import_header' ),
'grid' => array( 'import_field',
'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12',
'import_field13',
'import_field14',
'import_field15',
'import_field16',
'import_field17',
'import_field18',
'import_field19',
'import_field20',
'import_field21',
'import_field22' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'import_header' => 'top',
'import_field' => 'grid',
'import_field1' => 'grid',
'import_field2' => 'grid',
'import_field3' => 'grid',
'import_field4' => 'grid',
'import_field5' => 'grid',
'import_field6' => 'grid',
'import_field7' => 'grid',
'import_field8' => 'grid',
'import_field9' => 'grid',
'import_field10' => 'grid',
'import_field11' => 'grid',
'import_field12' => 'grid',
'import_field13' => 'grid',
'import_field14' => 'grid',
'import_field15' => 'grid',
'import_field16' => 'grid',
'import_field17' => 'grid',
'import_field18' => 'grid',
'import_field19' => 'grid',
'import_field20' => 'grid',
'import_field21' => 'grid',
'import_field22' => 'grid' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'import_header' => array( 'import_header' ),
'import_field' => array( 'import_field',
'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12',
'import_field13',
'import_field14',
'import_field15',
'import_field16',
'import_field17',
'import_field18',
'import_field19',
'import_field20',
'import_field21',
'import_field22' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'import',
'type' => 'import',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'import-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_header' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'import-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_field',
'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12',
'import_field13',
'import_field14',
'import_field15',
'import_field16',
'import_field17',
'import_field18',
'import_field19',
'import_field20',
'import_field21',
'import_field22' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'import_header' => array( 'type' => 'import_header' ),
'import_field' => array( 'field' => 'Code',
'type' => 'import_field' ),
'import_field1' => array( 'field' => 'CodeD',
'type' => 'import_field' ),
'import_field2' => array( 'field' => 'VirtualCode',
'type' => 'import_field' ),
'import_field3' => array( 'field' => 'Tdate',
'type' => 'import_field' ),
'import_field4' => array( 'field' => 'Status',
'type' => 'import_field' ),
'import_field5' => array( 'field' => 'PartyCode',
'type' => 'import_field' ),
'import_field6' => array( 'field' => 'StoreCode',
'type' => 'import_field' ),
'import_field7' => array( 'field' => 'ProductCode',
'type' => 'import_field' ),
'import_field8' => array( 'field' => 'ProductGroupCode',
'type' => 'import_field' ),
'import_field9' => array( 'field' => 'UnitCode',
'type' => 'import_field' ),
'import_field10' => array( 'field' => 'Qty',
'type' => 'import_field' ),
'import_field11' => array( 'field' => 'Rate',
'type' => 'import_field' ),
'import_field12' => array( 'field' => 'Amount',
'type' => 'import_field' ),
'import_field13' => array( 'field' => 'Remarks',
'type' => 'import_field' ),
'import_field14' => array( 'field' => 'UserName',
'type' => 'import_field' ),
'import_field15' => array( 'field' => 'CreateDate',
'type' => 'import_field' ),
'import_field16' => array( 'field' => 'CreateTime',
'type' => 'import_field' ),
'import_field17' => array( 'field' => 'UpdateUser',
'type' => 'import_field' ),
'import_field18' => array( 'field' => 'UpdateDate',
'type' => 'import_field' ),
'import_field19' => array( 'field' => 'UpdateTime',
'type' => 'import_field' ),
'import_field20' => array( 'field' => 'Block',
'type' => 'import_field' ),
'import_field21' => array( 'field' => 'BuCode',
'type' => 'import_field' ),
'import_field22' => array( 'field' => 'TotalNos',
'type' => 'import_field' ) ),
'dbProps' => array(  ),
'version' => 11,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right' );
		?>