<?php
			$optionsArray = array( 'totals' => array( 'ID' => array( 'totalsType' => '' ),
'Code' => array( 'totalsType' => '' ),
'TMonth' => array( 'totalsType' => '' ),
'TYear' => array( 'totalsType' => '' ),
'BookCode' => array( 'totalsType' => '' ),
'BookID' => array( 'totalsType' => '' ),
'VirtualCode' => array( 'totalsType' => '' ),
'TBook' => array( 'totalsType' => '' ),
'TType' => array( 'totalsType' => '' ),
'TDate' => array( 'totalsType' => '' ),
'BUnit' => array( 'totalsType' => '' ),
'Status' => array( 'totalsType' => '' ),
'PartyCode' => array( 'totalsType' => '' ),
'TotalAmount' => array( 'totalsType' => '' ),
'FreightAccountCode' => array( 'totalsType' => '' ),
'FreightCharges' => array( 'totalsType' => '' ),
'LaborAccountCode' => array( 'totalsType' => '' ),
'LaborCharges' => array( 'totalsType' => '' ),
'SaleTaxAccCode' => array( 'totalsType' => '' ),
'SaleTaxRate' => array( 'totalsType' => '' ),
'SaleTaxAmount' => array( 'totalsType' => '' ),
'DiscountAccCode' => array( 'totalsType' => '' ),
'DiscountRemarks' => array( 'totalsType' => '' ),
'DiscountRate' => array( 'totalsType' => '' ),
'DiscountAmount' => array( 'totalsType' => '' ),
'GrandTotal' => array( 'totalsType' => '' ),
'SaleMenCode' => array( 'totalsType' => '' ),
'Commission' => array( 'totalsType' => '' ),
'Remarks' => array( 'totalsType' => '' ),
'UserName' => array( 'totalsType' => '' ),
'CreateDate' => array( 'totalsType' => '' ),
'CreateTime' => array( 'totalsType' => '' ),
'UpdateUser' => array( 'totalsType' => '' ),
'UpdateDate' => array( 'totalsType' => '' ),
'UpdateTime' => array( 'totalsType' => '' ),
'Block' => array( 'totalsType' => '' ) ),
'fields' => array( 'gridFields' => array( 'ID',
'Code',
'TMonth',
'TYear',
'BookCode',
'BookID',
'VirtualCode',
'TBook',
'TType',
'TDate',
'BUnit',
'Status',
'PartyCode',
'TotalAmount',
'FreightAccountCode',
'FreightCharges',
'LaborAccountCode',
'LaborCharges',
'SaleTaxAccCode',
'SaleTaxRate',
'SaleTaxAmount',
'DiscountAccCode',
'DiscountRemarks',
'DiscountRate',
'DiscountAmount',
'GrandTotal',
'SaleMenCode',
'Commission',
'Remarks',
'UserName',
'CreateDate',
'CreateTime',
'UpdateUser',
'UpdateDate',
'UpdateTime',
'Block' ),
'exportFields' => array( 'ID',
'Code',
'TMonth',
'TYear',
'BookCode',
'BookID',
'VirtualCode',
'TBook',
'TType',
'TDate',
'BUnit',
'Status',
'PartyCode',
'TotalAmount',
'FreightAccountCode',
'FreightCharges',
'LaborAccountCode',
'LaborCharges',
'SaleTaxAccCode',
'SaleTaxRate',
'SaleTaxAmount',
'DiscountAccCode',
'DiscountRemarks',
'DiscountRate',
'DiscountAmount',
'GrandTotal',
'SaleMenCode',
'Commission',
'Remarks',
'UserName',
'CreateDate',
'CreateTime',
'UpdateUser',
'UpdateDate',
'UpdateTime',
'Block' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'ID' => array( 'export_field' ),
'Code' => array( 'export_field1' ),
'TMonth' => array( 'export_field2' ),
'TYear' => array( 'export_field3' ),
'BookCode' => array( 'export_field4' ),
'BookID' => array( 'export_field5' ),
'VirtualCode' => array( 'export_field6' ),
'TBook' => array( 'export_field7' ),
'TType' => array( 'export_field8' ),
'TDate' => array( 'export_field9' ),
'BUnit' => array( 'export_field10' ),
'Status' => array( 'export_field11' ),
'PartyCode' => array( 'export_field12' ),
'TotalAmount' => array( 'export_field13' ),
'FreightAccountCode' => array( 'export_field14' ),
'FreightCharges' => array( 'export_field15' ),
'LaborAccountCode' => array( 'export_field16' ),
'LaborCharges' => array( 'export_field17' ),
'SaleTaxAccCode' => array( 'export_field18' ),
'SaleTaxRate' => array( 'export_field19' ),
'SaleTaxAmount' => array( 'export_field20' ),
'DiscountAccCode' => array( 'export_field21' ),
'DiscountRemarks' => array( 'export_field22' ),
'DiscountRate' => array( 'export_field23' ),
'DiscountAmount' => array( 'export_field24' ),
'GrandTotal' => array( 'export_field25' ),
'SaleMenCode' => array( 'export_field26' ),
'Commission' => array( 'export_field27' ),
'Remarks' => array( 'export_field28' ),
'UserName' => array( 'export_field29' ),
'CreateDate' => array( 'export_field30' ),
'CreateTime' => array( 'export_field31' ),
'UpdateUser' => array( 'export_field32' ),
'UpdateDate' => array( 'export_field33' ),
'UpdateTime' => array( 'export_field34' ),
'Block' => array( 'export_field35' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'export_header' ),
'grid' => array( 'export_field',
'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field14',
'export_field15',
'export_field16',
'export_field17',
'export_field18',
'export_field19',
'export_field20',
'export_field21',
'export_field22',
'export_field23',
'export_field24',
'export_field25',
'export_field26',
'export_field27',
'export_field28',
'export_field29',
'export_field30',
'export_field31',
'export_field32',
'export_field33',
'export_field34',
'export_field35' ),
'footer' => array( 'export_export',
'export_cancel' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'export_header' => 'top',
'export_field' => 'grid',
'export_field1' => 'grid',
'export_field2' => 'grid',
'export_field3' => 'grid',
'export_field4' => 'grid',
'export_field5' => 'grid',
'export_field6' => 'grid',
'export_field7' => 'grid',
'export_field8' => 'grid',
'export_field9' => 'grid',
'export_field10' => 'grid',
'export_field11' => 'grid',
'export_field12' => 'grid',
'export_field13' => 'grid',
'export_field14' => 'grid',
'export_field15' => 'grid',
'export_field16' => 'grid',
'export_field17' => 'grid',
'export_field18' => 'grid',
'export_field19' => 'grid',
'export_field20' => 'grid',
'export_field21' => 'grid',
'export_field22' => 'grid',
'export_field23' => 'grid',
'export_field24' => 'grid',
'export_field25' => 'grid',
'export_field26' => 'grid',
'export_field27' => 'grid',
'export_field28' => 'grid',
'export_field29' => 'grid',
'export_field30' => 'grid',
'export_field31' => 'grid',
'export_field32' => 'grid',
'export_field33' => 'grid',
'export_field34' => 'grid',
'export_field35' => 'grid',
'export_export' => 'footer',
'export_cancel' => 'footer' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'export_header' => array( 'export_header' ),
'export_export' => array( 'export_export' ),
'export_cancel' => array( 'export_cancel' ),
'export_field' => array( 'export_field',
'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field14',
'export_field15',
'export_field16',
'export_field17',
'export_field18',
'export_field19',
'export_field20',
'export_field21',
'export_field22',
'export_field23',
'export_field24',
'export_field25',
'export_field26',
'export_field27',
'export_field28',
'export_field29',
'export_field30',
'export_field31',
'export_field32',
'export_field33',
'export_field34',
'export_field35' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'export' => array( 'format' => 2,
'selectFields' => false,
'delimiter' => ',',
'selectDelimiter' => false,
'exportFileTypes' => array( 'excel' => true,
'word' => true,
'csv' => true,
'xml' => false ) ) );
			$pageArray = array( 'id' => 'export',
'type' => 'export',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'export-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_header' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'export-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_field',
'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field14',
'export_field15',
'export_field16',
'export_field17',
'export_field18',
'export_field19',
'export_field20',
'export_field21',
'export_field22',
'export_field23',
'export_field24',
'export_field25',
'export_field26',
'export_field27',
'export_field28',
'export_field29',
'export_field30',
'export_field31',
'export_field32',
'export_field33',
'export_field34',
'export_field35' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'footer' => array( 'modelId' => 'export-footer',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ),
'c2' => array( 'model' => 'c2',
'items' => array( 'export_export',
'export_cancel' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'export_header' => array( 'type' => 'export_header' ),
'export_export' => array( 'type' => 'export_export' ),
'export_cancel' => array( 'type' => 'export_cancel' ),
'export_field' => array( 'field' => 'ID',
'type' => 'export_field' ),
'export_field1' => array( 'field' => 'Code',
'type' => 'export_field' ),
'export_field2' => array( 'field' => 'TMonth',
'type' => 'export_field' ),
'export_field3' => array( 'field' => 'TYear',
'type' => 'export_field' ),
'export_field4' => array( 'field' => 'BookCode',
'type' => 'export_field' ),
'export_field5' => array( 'field' => 'BookID',
'type' => 'export_field' ),
'export_field6' => array( 'field' => 'VirtualCode',
'type' => 'export_field' ),
'export_field7' => array( 'field' => 'TBook',
'type' => 'export_field' ),
'export_field8' => array( 'field' => 'TType',
'type' => 'export_field' ),
'export_field9' => array( 'field' => 'TDate',
'type' => 'export_field' ),
'export_field10' => array( 'field' => 'BUnit',
'type' => 'export_field' ),
'export_field11' => array( 'field' => 'Status',
'type' => 'export_field' ),
'export_field12' => array( 'field' => 'PartyCode',
'type' => 'export_field' ),
'export_field13' => array( 'field' => 'TotalAmount',
'type' => 'export_field' ),
'export_field14' => array( 'field' => 'FreightAccountCode',
'type' => 'export_field' ),
'export_field15' => array( 'field' => 'FreightCharges',
'type' => 'export_field' ),
'export_field16' => array( 'field' => 'LaborAccountCode',
'type' => 'export_field' ),
'export_field17' => array( 'field' => 'LaborCharges',
'type' => 'export_field' ),
'export_field18' => array( 'field' => 'SaleTaxAccCode',
'type' => 'export_field' ),
'export_field19' => array( 'field' => 'SaleTaxRate',
'type' => 'export_field' ),
'export_field20' => array( 'field' => 'SaleTaxAmount',
'type' => 'export_field' ),
'export_field21' => array( 'field' => 'DiscountAccCode',
'type' => 'export_field' ),
'export_field22' => array( 'field' => 'DiscountRemarks',
'type' => 'export_field' ),
'export_field23' => array( 'field' => 'DiscountRate',
'type' => 'export_field' ),
'export_field24' => array( 'field' => 'DiscountAmount',
'type' => 'export_field' ),
'export_field25' => array( 'field' => 'GrandTotal',
'type' => 'export_field' ),
'export_field26' => array( 'field' => 'SaleMenCode',
'type' => 'export_field' ),
'export_field27' => array( 'field' => 'Commission',
'type' => 'export_field' ),
'export_field28' => array( 'field' => 'Remarks',
'type' => 'export_field' ),
'export_field29' => array( 'field' => 'UserName',
'type' => 'export_field' ),
'export_field30' => array( 'field' => 'CreateDate',
'type' => 'export_field' ),
'export_field31' => array( 'field' => 'CreateTime',
'type' => 'export_field' ),
'export_field32' => array( 'field' => 'UpdateUser',
'type' => 'export_field' ),
'export_field33' => array( 'field' => 'UpdateDate',
'type' => 'export_field' ),
'export_field34' => array( 'field' => 'UpdateTime',
'type' => 'export_field' ),
'export_field35' => array( 'field' => 'Block',
'type' => 'export_field' ) ),
'dbProps' => array(  ),
'version' => 11,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'exportFormat' => 2,
'exportDelimiter' => ',',
'exportSelectDelimiter' => false,
'exportSelectFields' => false );
		?>