<?php
			$optionsArray = array( 'totals' => array( 'Code' => array( 'totalsType' => '' ),
'CodeD' => array( 'totalsType' => '' ),
'VirtualCode' => array( 'totalsType' => '' ),
'Tdate' => array( 'totalsType' => '' ),
'Status' => array( 'totalsType' => '' ),
'PartyCode' => array( 'totalsType' => '' ),
'StoreCode' => array( 'totalsType' => '' ),
'ProductCode' => array( 'totalsType' => '' ),
'ProductGroupCode' => array( 'totalsType' => '' ),
'UnitCode' => array( 'totalsType' => '' ),
'Qty' => array( 'totalsType' => '' ),
'Rate' => array( 'totalsType' => '' ),
'Amount' => array( 'totalsType' => '' ),
'Remarks' => array( 'totalsType' => '' ),
'UserName' => array( 'totalsType' => '' ),
'CreateDate' => array( 'totalsType' => '' ),
'CreateTime' => array( 'totalsType' => '' ),
'UpdateUser' => array( 'totalsType' => '' ),
'UpdateDate' => array( 'totalsType' => '' ),
'UpdateTime' => array( 'totalsType' => '' ),
'Block' => array( 'totalsType' => '' ),
'BuCode' => array( 'totalsType' => '' ),
'TotalNos' => array( 'totalsType' => '' ) ),
'fields' => array( 'gridFields' => array( 'Code',
'CodeD',
'VirtualCode',
'Tdate',
'Status',
'PartyCode',
'StoreCode',
'ProductCode',
'ProductGroupCode',
'UnitCode',
'Qty',
'Rate',
'Amount',
'Remarks',
'UserName',
'CreateDate',
'CreateTime',
'UpdateUser',
'UpdateDate',
'UpdateTime',
'Block',
'BuCode',
'TotalNos' ),
'exportFields' => array( 'Code',
'CodeD',
'VirtualCode',
'Tdate',
'Status',
'PartyCode',
'StoreCode',
'ProductCode',
'ProductGroupCode',
'UnitCode',
'Qty',
'Rate',
'Amount',
'Remarks',
'UserName',
'CreateDate',
'CreateTime',
'UpdateUser',
'UpdateDate',
'UpdateTime',
'Block',
'BuCode',
'TotalNos' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'Code' => array( 'export_field' ),
'CodeD' => array( 'export_field1' ),
'VirtualCode' => array( 'export_field2' ),
'Tdate' => array( 'export_field3' ),
'Status' => array( 'export_field4' ),
'PartyCode' => array( 'export_field5' ),
'StoreCode' => array( 'export_field6' ),
'ProductCode' => array( 'export_field7' ),
'ProductGroupCode' => array( 'export_field8' ),
'UnitCode' => array( 'export_field9' ),
'Qty' => array( 'export_field10' ),
'Rate' => array( 'export_field11' ),
'Amount' => array( 'export_field12' ),
'Remarks' => array( 'export_field13' ),
'UserName' => array( 'export_field14' ),
'CreateDate' => array( 'export_field15' ),
'CreateTime' => array( 'export_field16' ),
'UpdateUser' => array( 'export_field17' ),
'UpdateDate' => array( 'export_field18' ),
'UpdateTime' => array( 'export_field19' ),
'Block' => array( 'export_field20' ),
'BuCode' => array( 'export_field21' ),
'TotalNos' => array( 'export_field22' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'export_header' ),
'grid' => array( 'export_field',
'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field14',
'export_field15',
'export_field16',
'export_field17',
'export_field18',
'export_field19',
'export_field20',
'export_field21',
'export_field22' ),
'footer' => array( 'export_export',
'export_cancel' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'export_header' => 'top',
'export_field' => 'grid',
'export_field1' => 'grid',
'export_field2' => 'grid',
'export_field3' => 'grid',
'export_field4' => 'grid',
'export_field5' => 'grid',
'export_field6' => 'grid',
'export_field7' => 'grid',
'export_field8' => 'grid',
'export_field9' => 'grid',
'export_field10' => 'grid',
'export_field11' => 'grid',
'export_field12' => 'grid',
'export_field13' => 'grid',
'export_field14' => 'grid',
'export_field15' => 'grid',
'export_field16' => 'grid',
'export_field17' => 'grid',
'export_field18' => 'grid',
'export_field19' => 'grid',
'export_field20' => 'grid',
'export_field21' => 'grid',
'export_field22' => 'grid',
'export_export' => 'footer',
'export_cancel' => 'footer' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'export_header' => array( 'export_header' ),
'export_export' => array( 'export_export' ),
'export_cancel' => array( 'export_cancel' ),
'export_field' => array( 'export_field',
'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field14',
'export_field15',
'export_field16',
'export_field17',
'export_field18',
'export_field19',
'export_field20',
'export_field21',
'export_field22' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'export' => array( 'format' => 2,
'selectFields' => false,
'delimiter' => ',',
'selectDelimiter' => false,
'exportFileTypes' => array( 'excel' => true,
'word' => true,
'csv' => true,
'xml' => false ) ) );
			$pageArray = array( 'id' => 'export',
'type' => 'export',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'export-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_header' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'export-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_field',
'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field14',
'export_field15',
'export_field16',
'export_field17',
'export_field18',
'export_field19',
'export_field20',
'export_field21',
'export_field22' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'footer' => array( 'modelId' => 'export-footer',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ),
'c2' => array( 'model' => 'c2',
'items' => array( 'export_export',
'export_cancel' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'export_header' => array( 'type' => 'export_header' ),
'export_export' => array( 'type' => 'export_export' ),
'export_cancel' => array( 'type' => 'export_cancel' ),
'export_field' => array( 'field' => 'Code',
'type' => 'export_field' ),
'export_field1' => array( 'field' => 'CodeD',
'type' => 'export_field' ),
'export_field2' => array( 'field' => 'VirtualCode',
'type' => 'export_field' ),
'export_field3' => array( 'field' => 'Tdate',
'type' => 'export_field' ),
'export_field4' => array( 'field' => 'Status',
'type' => 'export_field' ),
'export_field5' => array( 'field' => 'PartyCode',
'type' => 'export_field' ),
'export_field6' => array( 'field' => 'StoreCode',
'type' => 'export_field' ),
'export_field7' => array( 'field' => 'ProductCode',
'type' => 'export_field' ),
'export_field8' => array( 'field' => 'ProductGroupCode',
'type' => 'export_field' ),
'export_field9' => array( 'field' => 'UnitCode',
'type' => 'export_field' ),
'export_field10' => array( 'field' => 'Qty',
'type' => 'export_field' ),
'export_field11' => array( 'field' => 'Rate',
'type' => 'export_field' ),
'export_field12' => array( 'field' => 'Amount',
'type' => 'export_field' ),
'export_field13' => array( 'field' => 'Remarks',
'type' => 'export_field' ),
'export_field14' => array( 'field' => 'UserName',
'type' => 'export_field' ),
'export_field15' => array( 'field' => 'CreateDate',
'type' => 'export_field' ),
'export_field16' => array( 'field' => 'CreateTime',
'type' => 'export_field' ),
'export_field17' => array( 'field' => 'UpdateUser',
'type' => 'export_field' ),
'export_field18' => array( 'field' => 'UpdateDate',
'type' => 'export_field' ),
'export_field19' => array( 'field' => 'UpdateTime',
'type' => 'export_field' ),
'export_field20' => array( 'field' => 'Block',
'type' => 'export_field' ),
'export_field21' => array( 'field' => 'BuCode',
'type' => 'export_field' ),
'export_field22' => array( 'field' => 'TotalNos',
'type' => 'export_field' ) ),
'dbProps' => array(  ),
'version' => 11,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'exportFormat' => 2,
'exportDelimiter' => ',',
'exportSelectDelimiter' => false,
'exportSelectFields' => false );
		?>