<?php

/**
 * 	Dear developer!
 *	Never modify events.php file, it is autogenerated.
 *  Modify PHP/EventTemplates/events.txt instead.
 *
 */

 class eventclass_gltd  extends eventsBase
{
	function __construct()
	{
	// fill list of events
		$this->events["BeforeAdd"]=true;


	}

//	handlers

		
		
		
		
		
		
		
		
		
		
		
		
		
				// Before record added
function BeforeAdd(&$values, &$message, $inline, $pageObject)
{

		$code="";
$virtual_code="";


if($values['TType'] == "J.v") {
$values["CreateDate"] = now();
$values["CreateTime"] = now();


$rs = DB::Query("SELECT * FROM gltd WHERE (TType = 'J.v') ORDER BY ID DESC LIMIT 1");
$record = $rs->fetchAssoc();
if (!$record) {
			$code="1".$currentYear."7";
			$virtual_code="1-".$currentYear."-7";
} else {
			$get_virtual_code = $record["VirtualCode"];

			$parts = explode('-', $get_virtual_code);

			$serial = (int)$parts[0] + 1;

			$code=$serial.$currentYear."7";

			$virtual_code=$serial."-".$currentYear."-7";
}

$values['Code'] = $code;
$values['VirtualCode'] = $virtual_code;
// Place event code here.
// Use "Add Action" button to add code snippets.
}
return true;
;		
} // function BeforeAdd

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		



}
?>
