<?php

/**
 * 	Dear developer!
 *	Never modify events.php file, it is autogenerated.
 *  Modify PHP/EventTemplates/events.txt instead.
 *
 */

 class eventclass_paccounts  extends eventsBase
{
	function __construct()
	{
	// fill list of events
		$this->events["AfterAdd"]=true;

		$this->events["AfterEdit"]=true;


	}

//	handlers

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// After record added
function AfterAdd(&$values, &$keys, $inline, $pageObject)
{

		$data = array();
$keyvalues = array();
$data["Code"] = "1".$values["ID"]."".$values["CoaCode"]."".$values["AccSubCode"];
$data["VirtualCode"] = "1-".$values["ID"]."-".$values["CoaCode"]."-".$values["AccSubCode"];
$keyvalues["id"] = $values["ID"];
DB::Update("pAccounts", $data, $keyvalues );

// Place event code here.
// Use "Add Action" button to add code snippets.
;		
} // function AfterAdd

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// After record updated
function AfterEdit(&$values, $where, &$oldvalues, &$keys, $inline, $pageObject)
{

		$data = array();
$keyvalues = array();
$data["Code"] = "1".$values["ID"]."".$values["CoaCode"]."".$values["AccSubCode"];
$data["VirtualCode"] = "1-".$values["ID"]."-".$values["CoaCode"]."-".$values["AccSubCode"];
$keyvalues["id"] = $values["ID"];
DB::Update("pAccounts", $data, $keyvalues );

// Place event code here.
// Use "Add Action" button to add code snippets.
;		
} // function AfterEdit

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		



}
?>
