<?php

/**
 * 	Dear developer!
 *	Never modify events.php file, it is autogenerated.
 *  Modify PHP/EventTemplates/events.txt instead.
 *
 */

 class eventclass_pbank  extends eventsBase
{
	function __construct()
	{
	// fill list of events
		$this->events["AfterAdd"]=true;

		$this->events["AfterEdit"]=true;


	}

//	handlers

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// After record added
function AfterAdd(&$values, &$keys, $inline, $pageObject)
{

		

try {
    // Extract values from form
		$id = (int)$values["id"];
		$code = (int)$values["id"]; // e.g., 712

		// Combine with hyphen
		$formattedCode =  sqlVal("1-9-".$id);

		$bunit = (int)$values['business_id'];
		$block = (int)$values["Block"];
		$group_id = (int)$values['group_id'];

		$oldcode = sqlVal($values["OldCode"]);
		$name = sqlVal($values["Name"]);
		$remarks = sqlVal($values["Remarks"]);
		$user = sqlVal($values["UserName"]);
		$now = sqlVal($values["CreateDate"]);

    // Call the stored procedure
    $sql = "CALL 	sp_insert_bank_pAccount("
    . $id . ", "
    . $bunit . ", "
    . $code . ", "
    . $formattedCode . ", "
    . $group_id . ")";
    DB::Query($sql);

} catch (Exception $e) {
    // If procedure fails, delete the just-added customer record
    DB::Delete("pBank", array("id" => $values["id"]));
    // Optional: Show error to user
    echo "Account creation failed: " . $e->getMessage();
}

// Place event code here.
// Use "Add Action" button to add code snippets.
;		
} // function AfterAdd

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// After record updated
function AfterEdit(&$values, $where, &$oldvalues, &$keys, $inline, $pageObject)
{

		
$keyvalues = array();
$data["UpdateDate"] = now();
$data["UpdateTime"] = now();
$keyvalues["id"] = $values['ID'];
DB::Update("pBank", $data, $keyvalues );





try {
    // Extract values from form
		$id = (int)$values["id"];
		$code = (int)$values["id"]; // e.g., 712

		// Combine with hyphen
		$formattedCode =  sqlVal("1-9-".$id);

		$bunit = (int)$values['business_id'];
		$block = (int)$values["Block"];
		$group_id = (int)$values['group_id'];

		$oldcode = sqlVal($values["OldCode"]);
		$name = sqlVal($values["Name"]);
		$remarks = sqlVal($values["Remarks"]);
		$user = sqlVal($values["UserName"]);
		$now = sqlVal($values["CreateDate"]);

    // Call the stored procedure
    $sql = "CALL 	UpdatepBank("
    . $id . ", "
    . $bunit . ", "
    . $code . ", "
    . $formattedCode . ", "
    . $group_id . ")";
    DB::Query($sql);

} catch (Exception $e) {
    // If procedure fails, delete the just-added customer record
    DB::Delete("pBank", array("id" => $values["id"]));
    // Optional: Show error to user
    echo "Account creation failed: " . $e->getMessage();
}

// Place event code here.
// Use "Add Action" button to add code snippets.

// Place event code here.
// Use "Add Action" button to add code snippets.
// Place event code here.
// Use "Add Action" button to add code snippets.
;		
} // function AfterEdit

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		



}
?>
