<?php

/**
 * 	Dear developer!
 *	Never modify events.php file, it is autogenerated.
 *  Modify PHP/EventTemplates/events.txt instead.
 *
 */

 class eventclass_psupplier  extends eventsBase
{
	function __construct()
	{
	// fill list of events
		$this->events["AfterAdd"]=true;

		$this->events["BeforeAdd"]=true;

		$this->events["BeforeEdit"]=true;

		$this->events["AfterEdit"]=true;


	}

//	handlers

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// After record added
function AfterAdd(&$values, &$keys, $inline, $pageObject)
{

		$code = "8".$values['ID'];
$code_in_number = number_format($code);

// Place event code here.
// Use "Add Action" button to add code snippets.$data = array();



try {
    $id = (int)$values["ID"];
    $bunit = (int)$values["BUnit"];
    $block = (int)$values["Block"];
		$code = (int)$values["Code"]; // e.g., 712
		$formattedCode =  sqlVal("2-8-".$code);
    $oldcode = sqlVal($values["OldCode"]);
    $name = sqlVal($values["Name"]);
    $remarks = sqlVal($values["Remarks"]);
    $user = sqlVal($values["UserName"]);
    $now = sqlVal($values["CreateDate"]);

    $sql = "CALL CreateSupplierpAccounts("
        . $id . ", "
        . $bunit . ", "
        . $oldcode . ", "
        . $name . ", "
        . $remarks . ", "
        . $user . ", "
        . $now . ", "
        . $now . ", "
				 . $block . ", "
				 . $code . ", "
				 . $formattedCode . ")";
    
    DB::Query($sql);

} catch (Exception $e) {
    DB::Delete("pSupplier", ["ID" => $values["ID"]]);
    echo "Account creation failed: " . $e->getMessage();
}

// Place event code here.
// Use "Add Action" button to add code snippets.

;		
} // function AfterAdd

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
				// Before record added
function BeforeAdd(&$values, &$message, $inline, $pageObject)
{

				$values["CreateDate"] = now();
$values["CreateTime"] = now();


$rs = DB::Query("SELECT * FROM pSupplier ORDER BY ID DESC LIMIT 1");
$record = $rs->fetchAssoc();
if (!$record) {
    $values["Code"] = 81; // No records exist yet
} else {
    $code = $record["Code"]; // e.g., "712"

    $prefix = substr($code, 0, 1); // "7"
    $numberPart = substr($code, 1); // "12"
    $incremented = intval($numberPart) + 1; // 13
    $newCode = $prefix . $incremented;

    $values["Code"] = $newCode;
}

// Place event code here.
// Use "Add Action" button to add code snippets.


return true;
;		
} // function BeforeAdd

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// Before record updated
function BeforeEdit(&$values, $where, &$oldvalues, &$keys, &$message, $inline, $pageObject)
{

		$values["UpdateDate"] = now();
$values["UpdateTime"] = now();

// Place event code here.
// Use "Add Action" button to add code snippets.

return true;
;		
} // function BeforeEdit

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// After record updated
function AfterEdit(&$values, $where, &$oldvalues, &$keys, $inline, $pageObject)
{

				try {
    $id = (int)$values["id"];
    $bunit = (int)$values["BUnit"];
    $block = (int)$values["Block"];

    $oldcode = sqlVal($values["OldCode"]);
    $name = sqlVal($values["Name"]);
    $remarks = sqlVal($values["Remarks"]);
    $user = sqlVal($values["UserName"]);
    $now = sqlVal($values["CreateDate"]); // or UpdateDate

    $sql = "CALL UpdateSupplierpAccounts("
        . $id . ", "
        . $bunit . ", "
        . $oldcode . ", "
        . $name . ", "
        . $remarks . ", "
        . $user . ", "
        . $now . ", "
        . $now . ", "
        . $block . ")";
    
    DB::Query($sql);

} catch (Exception $e) {
    echo "Supplier account update failed: " . $e->getMessage();
}

// Place event code here.
// Use "Add Action" button to add code snippets.
;		
} // function AfterEdit

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		



}
?>
