<?php
$securitySettings_var = array( 'providers' => array( array( 'type' => '%db',
'activationField' => '',
'active' => true,
'code' => '00',
'emailField' => '',
'extUserIdField' => null,
'fullnameField' => null,
'label' => array( 'text' => 'Database',
'type' => 0 ),
'name' => 'db',
'passwordField' => 'Password',
'resetDateField' => '',
'resetTokenField' => '',
'table' => array( 'connId' => 'karsaaz_pos_at_localhost',
'table' => 'umUserInfo' ),
'userGroupField' => 'LoginUserName',
'usernameField' => 'LoginUserName',
'userpicField' => null ) ),
'sessionControl' => array( 'lifeTime' => 15,
'sessionName' => 'J8S9yEk4807o3QaKBOh0',
'JWTSecret' => 's4XO94vYWkSDRhmBXhT2' ),
'registration' => array( 'passwordValidation' => array( 'strong' => false,
'minimumLength' => 8,
'uniqueCharacters' => 4,
'digitsAndSymbols' => 2,
'upperAndLowerCase' => false ),
'remindMethod' => 1,
'hashAlgorithm' => 0,
'changePwdPage' => false,
'hashPassword' => false,
'registerPage' => false,
'remindPage' => false ),
'captchaSettings' => array( 'captchaType' => 0,
'siteKey' => '',
'secretKey' => '',
'passesCount' => 5 ),
'emailSettings' => array( 'fromEmail' => '',
'usePHPDefinedSMTP' => false,
'useBuiltInMailer' => false,
'SMTPServer' => 'localhost',
'SMTPPort' => 25,
'SMTPUser' => '',
'SMTPPassword' => '',
'securityProtocol' => 0 ),
'advancedSecurity' => array( 'allowGuestLogin' => false ),
'auditAndLocking' => array( 'loggingTable' => array(  ),
'lockingTable' => array(  ),
'tables' => array(  ),
'loggingMode' => 0,
'loggingFile' => 'audit.log',
'logSecurityActions' => false,
'lockAfterUnsuccessfulLogin' => false,
'enableLocking' => false ),
'twoFactorSettings' => array( 'available' => false,
'required' => false,
'enable' => true,
'remember' => true,
'types' => array(  ),
'twoFactorField' => '',
'emailField' => '',
'phoneField' => '',
'codeField' => '',
'projectName' => '' ),
'projectName' => 'karsaaz_pos',
'loginDataSource' => 'umUserInfo',
'loginForm' => 0,
'dynamicPermissions' => true,
'dpTablePrefix' => 'karsaaz_pos1',
'dpTableConnId' => 'karsaaz_pos_at_localhost',
'hardcodedLogin' => false,
'enabled' => true,
'advancedSecurityAvailable' => true,
'userGroupsAvailable' => true,
'defaultProviderCode' => '00',
'adOnlyLogin' => false,
'dbProvider' => array( 'type' => '%db',
'activationField' => '',
'active' => true,
'code' => '00',
'emailField' => '',
'extUserIdField' => null,
'fullnameField' => null,
'label' => array( 'text' => 'Database',
'type' => 0 ),
'name' => 'db',
'passwordField' => 'Password',
'resetDateField' => '',
'resetTokenField' => '',
'table' => array( 'connId' => 'karsaaz_pos_at_localhost',
'table' => 'umUserInfo' ),
'userGroupField' => 'LoginUserName',
'usernameField' => 'LoginUserName',
'userpicField' => null ),
'adAdminGroups' => array(  ),
'showUserSource' => false,
'dbProviderCodes' => array( '00' ),
'notifications' => array(  ) );
?>