<?php
$dalTablepBU = array();
$dalTablepBU["Code"] = array("type"=>3,"varname"=>"Code", "name" => "Code", "autoInc" => "1");
$dalTablepBU["Name"] = array("type"=>200,"varname"=>"Name", "name" => "Name", "autoInc" => "0");
$dalTablepBU["ContactName"] = array("type"=>200,"varname"=>"ContactName", "name" => "ContactName", "autoInc" => "0");
$dalTablepBU["BusinessType"] = array("type"=>200,"varname"=>"BusinessType", "name" => "BusinessType", "autoInc" => "0");
$dalTablepBU["Address"] = array("type"=>200,"varname"=>"Address", "name" => "Address", "autoInc" => "0");
$dalTablepBU["Address2"] = array("type"=>200,"varname"=>"Address2", "name" => "Address2", "autoInc" => "0");
$dalTablepBU["Phone"] = array("type"=>200,"varname"=>"Phone", "name" => "Phone", "autoInc" => "0");
$dalTablepBU["Cell"] = array("type"=>200,"varname"=>"Cell", "name" => "Cell", "autoInc" => "0");
$dalTablepBU["Fax"] = array("type"=>200,"varname"=>"Fax", "name" => "Fax", "autoInc" => "0");
$dalTablepBU["EMail"] = array("type"=>200,"varname"=>"EMail", "name" => "EMail", "autoInc" => "0");
$dalTablepBU["WebAddress"] = array("type"=>200,"varname"=>"WebAddress", "name" => "WebAddress", "autoInc" => "0");
$dalTablepBU["CNIC"] = array("type"=>200,"varname"=>"CNIC", "name" => "CNIC", "autoInc" => "0");
$dalTablepBU["NTNNo"] = array("type"=>200,"varname"=>"NTNNo", "name" => "NTNNo", "autoInc" => "0");
$dalTablepBU["StnNo"] = array("type"=>200,"varname"=>"StnNo", "name" => "StnNo", "autoInc" => "0");
$dalTablepBU["CurrencyNo"] = array("type"=>5,"varname"=>"CurrencyNo", "name" => "CurrencyNo", "autoInc" => "0");
$dalTablepBU["BraNo"] = array("type"=>200,"varname"=>"BraNo", "name" => "BraNo", "autoInc" => "0");
$dalTablepBU["Remarks"] = array("type"=>200,"varname"=>"Remarks", "name" => "Remarks", "autoInc" => "0");
$dalTablepBU["CountryCode"] = array("type"=>5,"varname"=>"CountryCode", "name" => "CountryCode", "autoInc" => "0");
$dalTablepBU["ProvinceCode"] = array("type"=>5,"varname"=>"ProvinceCode", "name" => "ProvinceCode", "autoInc" => "0");
$dalTablepBU["CityCode"] = array("type"=>5,"varname"=>"CityCode", "name" => "CityCode", "autoInc" => "0");
$dalTablepBU["DivisionCode"] = array("type"=>5,"varname"=>"DivisionCode", "name" => "DivisionCode", "autoInc" => "0");
$dalTablepBU["DistrictCode"] = array("type"=>5,"varname"=>"DistrictCode", "name" => "DistrictCode", "autoInc" => "0");
$dalTablepBU["TahsileCode"] = array("type"=>5,"varname"=>"TahsileCode", "name" => "TahsileCode", "autoInc" => "0");
$dalTablepBU["MainAreaCode"] = array("type"=>5,"varname"=>"MainAreaCode", "name" => "MainAreaCode", "autoInc" => "0");
$dalTablepBU["SubAreaCode"] = array("type"=>5,"varname"=>"SubAreaCode", "name" => "SubAreaCode", "autoInc" => "0");
$dalTablepBU["NameInUrdu"] = array("type"=>200,"varname"=>"NameInUrdu", "name" => "NameInUrdu", "autoInc" => "0");
$dalTablepBU["RemarksInUrdu"] = array("type"=>200,"varname"=>"RemarksInUrdu", "name" => "RemarksInUrdu", "autoInc" => "0");
$dalTablepBU["Pic"] = array("type"=>128,"varname"=>"Pic", "name" => "Pic", "autoInc" => "0");
$dalTablepBU["PictureStatus"] = array("type"=>200,"varname"=>"PictureStatus", "name" => "PictureStatus", "autoInc" => "0");
$dalTablepBU["UserName"] = array("type"=>200,"varname"=>"UserName", "name" => "UserName", "autoInc" => "0");
$dalTablepBU["CreateDate"] = array("type"=>135,"varname"=>"CreateDate", "name" => "CreateDate", "autoInc" => "0");
$dalTablepBU["CreateTime"] = array("type"=>200,"varname"=>"CreateTime", "name" => "CreateTime", "autoInc" => "0");
$dalTablepBU["CreatePcName"] = array("type"=>200,"varname"=>"CreatePcName", "name" => "CreatePcName", "autoInc" => "0");
$dalTablepBU["CreatePCUser"] = array("type"=>200,"varname"=>"CreatePCUser", "name" => "CreatePCUser", "autoInc" => "0");
$dalTablepBU["CreateLoc"] = array("type"=>200,"varname"=>"CreateLoc", "name" => "CreateLoc", "autoInc" => "0");
$dalTablepBU["CreateDevice"] = array("type"=>200,"varname"=>"CreateDevice", "name" => "CreateDevice", "autoInc" => "0");
$dalTablepBU["UpdatePcUser"] = array("type"=>200,"varname"=>"UpdatePcUser", "name" => "UpdatePcUser", "autoInc" => "0");
$dalTablepBU["UpdateUser"] = array("type"=>200,"varname"=>"UpdateUser", "name" => "UpdateUser", "autoInc" => "0");
$dalTablepBU["UpdateDate"] = array("type"=>135,"varname"=>"UpdateDate", "name" => "UpdateDate", "autoInc" => "0");
$dalTablepBU["UpdateTime"] = array("type"=>200,"varname"=>"UpdateTime", "name" => "UpdateTime", "autoInc" => "0");
$dalTablepBU["UpdatePcName"] = array("type"=>200,"varname"=>"UpdatePcName", "name" => "UpdatePcName", "autoInc" => "0");
$dalTablepBU["UpdateLoc"] = array("type"=>200,"varname"=>"UpdateLoc", "name" => "UpdateLoc", "autoInc" => "0");
$dalTablepBU["UpdateDevice"] = array("type"=>200,"varname"=>"UpdateDevice", "name" => "UpdateDevice", "autoInc" => "0");
$dalTablepBU["TotalUpdate"] = array("type"=>5,"varname"=>"TotalUpdate", "name" => "TotalUpdate", "autoInc" => "0");
$dalTablepBU["Block"] = array("type"=>16,"varname"=>"Block", "name" => "Block", "autoInc" => "0");
$dalTablepBU["Lock"] = array("type"=>16,"varname"=>"Lock", "name" => "Lock", "autoInc" => "0");
$dalTablepBU["Hide"] = array("type"=>16,"varname"=>"Hide", "name" => "Hide", "autoInc" => "0");
$dalTablepBU["Bookmark"] = array("type"=>16,"varname"=>"Bookmark", "name" => "Bookmark", "autoInc" => "0");
$dalTablepBU["BMStatus"] = array("type"=>200,"varname"=>"BMStatus", "name" => "BMStatus", "autoInc" => "0");
$dalTablepBU["BMIConID"] = array("type"=>5,"varname"=>"BMIConID", "name" => "BMIConID", "autoInc" => "0");
$dalTablepBU["BMRowID"] = array("type"=>5,"varname"=>"BMRowID", "name" => "BMRowID", "autoInc" => "0");
$dalTablepBU["DBRowID"] = array("type"=>5,"varname"=>"DBRowID", "name" => "DBRowID", "autoInc" => "0");
$dalTablepBU["ECol1"] = array("type"=>5,"varname"=>"ECol1", "name" => "ECol1", "autoInc" => "0");
$dalTablepBU["VirtualCode"] = array("type"=>200,"varname"=>"VirtualCode", "name" => "VirtualCode", "autoInc" => "0");
$dalTablepBU["Code"]["key"]=true;

$dal_info["karsaaz_pos_at_localhost__pBU"] = &$dalTablepBU;
?>